version: "2"
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - misspell
    - unused
    - errcheck
    - gosec
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-use-default: false
  exclude:
    - "exported .* should have comment or be unexported"
    - "comment on exported .* should be of the form"
